export const products = {
  shoes: [
    {
      id: 1,
      name: "Winter body",
      description: [
        { Warranty: "15 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 120,
      offPrice: 120,
      discount: 0,
      image:
        "https://s6.uupload.ir/files/daniel-storek-jm-qked1gmi-unsplash_ja2.jpg",
      satisfaction: 86,
      colors: ["Red", "Blue", "Black"],
      size: [39, 40, 41, 42, 43],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Emma",
          id: 1,
          date: "Sat Jan 23 2023",
          text: "Very Good",
          scor: 4.5,
        },
        {
          name: "Ava",
          id: 2,
          date: "Sat Jan 24 2023",
          text: "normal",
          scor: 3,
        },
        {
          name: "Sofia",
          id: 3,
          date: "Sat Jan 25 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 2,
      name: "Adidas",
      description: [
        { Warranty: "12 months warranty" },
        { Quality: "fake" },
        { support: "Non-free shipping" },
      ],
      price: 110,
      offPrice: 100,
      discount: "9%",
      image:
        "https://s6.uupload.ir/files/andres-jasso-pqbl_mxmaue-unsplash_gkir.jpg",
      satisfaction: 80,
      colors: ["Blue", "Red"],
      size: [40, 41, 42, 43],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Grace",
          id: 1,
          date: "Sat Jan 26 2023",
          text: "normal",
          scor: 3.5,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 27 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 3,
      name: "Vans",
      description: [
        { Warranty: "8 months warranty" },
        { Quality: "fake" },
        { support: "Non-free shipping" },
      ],
      price: 99,
      offPrice: 89,
      discount: "10%",
      image:
        "https://s6.uupload.ir/files/maksim-larin-nopsc3nwtzy-unsplash_i0j6.jpg",
      satisfaction: 82,
      colors: ["Red", "Blue", "Pink"],
      size: [39, 40, 41],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Grace",
          id: 1,
          date: "Sat Jan 27 2023",
          text: "Very Good",
          scor: 4.5,
        },
        {
          name: "Ava",
          id: 2,
          date: "Sat Jan 28 2023",
          text: "normal",
          scor: 3,
        },
        {
          name: "Sofia",
          id: 3,
          date: "Sat Jan 28 2023",
          text: " bad",
          scor: 2,
        },
      ],
    },
    {
      id: 4,
      name: "White",
      description: [
        { Warranty: "20 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 260,
      offPrice: 220,
      discount: "15%",
      image: "https://s6.uupload.ir/files/revolt-164_6wvehfi-unsplash_xaog.jpg",
      satisfaction: 90,
      colors: ["Red", "Green", "Pink"],
      size: [38, 39, 40, 41],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Sofia",
          id: 1,
          date: "Sat Jan 27 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 5,
      name: "Croopped-shoe",
      description: [
        { Warranty: "19 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 150,
      offPrice: 150,
      discount: 0,
      image:
        "https://s6.uupload.ir/files/maksim-larin-ezdrvza1hzw-unsplash_nm8f.jpg",
      satisfaction: 93,
      colors: ["Red", "Blue", "Green"],
      size: [39, 40, 41, 42],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 27 2023",
          text: "normal",
          scor: 3,
        },
      ],
    },
    {
      id: 6,
      name: "Blues",
      description: [
        { warranty: "22 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 220,
      offPrice: 200,
      discount: "9%",
      image:
        "https://s6.uupload.ir/files/luis-felipe-lins-j2-waqdckus-unsplash_ku8a.jpg",
      satisfaction: 81,
      colors: ["Red", "Blue"],
      size: [39, 40, 41, 42],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: " shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Amelia",
          id: 1,
          date: "Sat Jan 26 2023",
          text: "normal",
          scor: 4,
        },
      ],
    },
    {
      id: 7,
      name: "Vans 1",
      description: [
        { Warranty: "8 months warranty" },
        { Quality: "fake" },
        { support: "Non-free shipping" },
      ],
      price: 99,
      offPrice: 89,
      discount: "10%",
      image:
        "https://s2.uupload.ir/files/pexels-shane-aldendorff-786003_(1)_ka7.jpg",
      satisfaction: 82,
      colors: ["Red", "Blue", "Pink"],
      size: [39, 40, 41],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 26 2023",
          text: "normal",
          scor: 3,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 27 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 8,
      name: "White 2",
      description: [
        { Warranty: "20 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 260,
      offPrice: 220,
      discount: "15%",
      image:
        "https://s2.uupload.ir/files/pexels-oluwaseun-duncan-186035_b7i9.jpg",
      satisfaction: 90,
      colors: ["Red", "Green", "Pink"],
      size: [38, 39, 40, 41],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 25 2023",
          text: "normal",
          scor: 3.7,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 27 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 9,
      name: "Croopped-shoe 2",
      description: [
        { Warranty: "19 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 150,
      offPrice: 150,
      discount: 0,
      image:
        "https://s2.uupload.ir/files/pexels-terje-sollie-298863_(1)_1ffa.jpg",
      satisfaction: 93,
      colors: ["Red", "Blue", "Green"],
      size: [39, 40, 41, 42],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 27 2023",
          text: "normal",
          scor: 3,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 28 2023",
          text: " Good",
          scor: 3,
        },
      ],
    },
    {
      id: 10,
      name: "Blues 2",
      description: [
        { warranty: "22 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 220,
      offPrice: 200,
      discount: "9%",
      image:
        "https://s2.uupload.ir/files/pexels-felipepelaquim-1895019_slru.jpg",
      satisfaction: 81,
      colors: ["Red", "Blue"],
      size: [39, 40, 41, 42],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: " shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 27 2023",
          text: "normal",
          scor: 3.5,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 27 2023",
          text: "very Good",
          scor: 5,
        },
      ],
    },
    {
      id: 11,
      name: "Blues 2",
      description: [
        { warranty: "22 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 220,
      offPrice: 200,
      discount: "9%",
      image: "https://s2.uupload.ir/files/pexels-mnz-1598505_bu1d.jpg",
      satisfaction: 81,
      colors: ["Red", "Blue"],
      size: [39, 40, 41, 42],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: " shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 24 2023",
          text: "normal",
          scor: 3,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 27 2023",
          text: "bad",
          scor: 2.5,
        },
      ],
    },
  ],
  campSupplies: [
    {
      id: 12,
      name: "Tent 1",
      description: [
        { Warranty: "15 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 130,
      offPrice: 120,
      discount: "10%",
      image:
        "https://s2.uupload.ir/files/pexels-dziana-hasanbekava-5589360_c3e.jpg",
      satisfaction: 86,
      colors: ["Red", "Blue", "Black"],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Emma",
          id: 1,
          date: "Sat Jan 24 2023",
          text: "Very Good",
          scor: 4.5,
        },
        {
          name: "Ava",
          id: 2,
          date: "Sat Jan 25 2023",
          text: "normal",
          scor: 3,
        },
        {
          name: "Sofia",
          id: 3,
          date: "Sat Jan 26 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 13,
      name: "Tent 2",
      description: [
        { Warranty: "12 months warranty" },
        { Quality: "fake" },
        { support: "Non-free shipping" },
      ],
      price: 150,
      offPrice: 130,
      discount: "9%",
      image: "https://s2.uupload.ir/files/pexels-josh-hild-2422265_fg4v.jpg",
      satisfaction: 80,
      colors: ["Blue", "Red"],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Grace",
          id: 1,
          date: "Sat Jan 27 2023",
          text: "normal",
          scor: 3.5,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 27 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 14,
      name: "Tent 3",
      description: [
        { Warranty: "8 months warranty" },
        { Quality: "fake" },
        { support: "Non-free shipping" },
      ],
      price: 109,
      offPrice: 99,
      discount: "10%",
      image:
        "https://s2.uupload.ir/files/pexels-raj-tatavarthy-111362_ub48.jpg",
      satisfaction: 82,
      colors: ["Red", "Blue"],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Grace",
          id: 1,
          date: "Sat Jan 27 2023",
          text: "Very Good",
          scor: 4.5,
        },
        {
          name: "Ava",
          id: 2,
          date: "Sat Jan 27 2023",
          text: "normal",
          scor: 3,
        },
        {
          name: "Sofia",
          id: 3,
          date: "Sat Jan 28 2023",
          text: " bad",
          scor: 2,
        },
      ],
    },
    {
      id: 15,
      name: "Tent 4",
      description: [
        { Warranty: "20 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 200,
      offPrice: 180,
      discount: "15%",
      image:
        "https://s2.uupload.ir/files/pexels-tobias-bjørkli-2340161_lbj4.jpg",
      satisfaction: 90,
      colors: ["Red", "Green"],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Sofia",
          id: 1,
          date: "Sat Jan 27 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 16,
      name: "Tent 5",
      description: [
        { Warranty: "19 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 150,
      offPrice: 140,
      discount: "9%",
      image:
        "https://s2.uupload.ir/files/pexels-vlad-bagacian-2819554_govc.jpg",
      satisfaction: 93,
      colors: ["Red", "Blue", "Green"],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 27 2023",
          text: "normal",
          scor: 3,
        },
      ],
    },
    {
      id: 17,
      name: "Kattle",
      description: [
        { warranty: "22 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 50,
      offPrice: 40,
      discount: "15%",
      image:
        "https://s2.uupload.ir/files/pexels-omar-ramadan-7572432_ee2r.jpg",
      satisfaction: 81,
      colors: ["Red", "Blue"],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: " shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Amelia",
          id: 1,
          date: "Sat Jan 27 2023",
          text: "normal",
          scor: 4,
        },
      ],
    },
    {
      id: 18,
      name: "Hammer",
      description: [
        { Warranty: "8 months warranty" },
        { Quality: "fake" },
        { support: "Non-free shipping" },
      ],
      price: 59,
      offPrice: 39,
      discount: "10%",
      image: "https://s2.uupload.ir/files/pexels-pixabay-209235_7tpd.jpg",
      satisfaction: 82,
      colors: ["Red", "Blue"],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 26 2023",
          text: "normal",
          scor: 3,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 27 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 19,
      name: "Kettle",
      description: [
        { Warranty: "20 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 40,
      offPrice: 30,
      discount: "20%",
      image: "https://s2.uupload.ir/files/pexels-uriel-mont-6271316_bl9d.jpg",
      satisfaction: 90,
      colors: ["Red", "Green"],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 23 2023",
          text: "normal",
          scor: 3.7,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 27 2023",
          text: " Good",
          scor: 4,
        },
      ],
    },
    {
      id: 20,
      name: "Knife",
      description: [
        { Warranty: "19 months warranty" },
        { Quality: "original" },
        { support: "free delivery" },
      ],
      price: 50,
      offPrice: 40,
      discount: "10%",
      image: "https://s2.uupload.ir/files/pexels-efecan-efe-8200209_ooxj.jpg",
      satisfaction: 93,
      colors: ["black", "Blue", "Green"],
      Property: [
        { Property: "material", Description: "cloth and Artificial leather" },
        { Property: "sole material", Description: "TPU" },
        { Property: "Insole", Description: "Replaceable" },
        { Property: "shoes", Description: "shoemaking" },
      ],
      comments: [
        {
          name: "Ava",
          id: 1,
          date: "Sat Jan 25 2023",
          text: "normal",
          scor: 3,
        },
        {
          name: "Sofia",
          id: 2,
          date: "Sat Jan 27 2023",
          text: " Good",
          scor: 3,
        },
      ],
    },
    
  ],
};
